<script>
  import { CONTEXTO_PADRAO } from './dados.js';
  import MinMax from './MinMax.svelte';
  let { contexto, onaplicar, oncancelar }=$props();
  let c=$state(structuredClone({...CONTEXTO_PADRAO,...(contexto??{}),dogs:{...CONTEXTO_PADRAO.dogs,...(contexto?.dogs??{})}}));
  const companhias=[['casal','Só nós dois'],['dogs','Com os dogs'],['filhos','Com filhos'],['pais','Com os pais'],['amigos','Com amigos']];
  const ocasioes=['','Aniversário','Aniversário de casamento','Dia dos Namorados','Dia das Mães','Dia dos Pais','Natal','Réveillon','Feriado','Celebração especial'];
  const adicionar=(campo)=>c[campo]=[...(c[campo]??[]),campo==='filhos'?{idade:0}:{idade:null,mobilidadeReduzida:false}];
  function selecionarCompanhia(id){c.companhia=id;if(id==='dogs'&&!c.dogs.quantidade)c.dogs.quantidade=1;if(id==='filhos'&&!c.filhos.length)adicionar('filhos');if(id==='pais'&&!c.pais.length)adicionar('pais');if(id==='amigos'&&!c.amigos)c.amigos=1}
</script>
<div class="backdrop"></div><section class="sheet"><button class="close" onclick={oncancelar}>×</button><small>ESTA PESQUISA</small><h2>Quem vai desta vez?</h2><div class="cards">{#each companhias as [id,label]}<button class:on={c.companhia===id} onclick={()=>selecionarCompanhia(id)}>{label}</button>{/each}</div>
{#if c.companhia==='dogs'}<h3>Dogs</h3><label>Quantidade<input type="number" min="1" bind:value={c.dogs.quantidade}/></label><label>Taxa máxima por animal R$<input type="number" min="0" bind:value={c.dogs.taxaMax}/></label><label class="check"><input type="checkbox" bind:checked={c.dogs.areaExterna}/> Área externa</label><p class="note">Mostraremos somente locais cuja aceitação de pets esteja confirmada.</p>{/if}
{#if c.companhia==='filhos'}<h3>Idades dos filhos</h3>{#each c.filhos as filho,i}<label>Filho {i+1}<input type="number" min="0" max="17" bind:value={filho.idade}/></label>{/each}<button class="add" onclick={()=>adicionar('filhos')}>+ Adicionar filho</button>{/if}
{#if c.companhia==='pais'}<h3>Pais</h3>{#each c.pais as pai,i}<div class="person"><label>Idade opcional<input type="number" min="0" bind:value={pai.idade}/></label><label class="check"><input type="checkbox" bind:checked={pai.mobilidadeReduzida}/> Mobilidade reduzida</label></div>{/each}<button class="add" onclick={()=>adicionar('pais')}>+ Adicionar pessoa</button>{/if}
{#if c.companhia==='amigos'}<label>Quantidade de amigos<input type="number" min="1" bind:value={c.amigos}/></label>{/if}
<h3>Ocasião e datas</h3><label>Ocasião<select bind:value={c.ocasiao}>{#each ocasioes as o}<option value={o}>{o||'Sem ocasião específica'}</option>{/each}</select></label><div class="two"><label>De<input type="date" bind:value={c.dataInicio}/></label><label>Até<input type="date" bind:value={c.dataFim}/></label></div><MinMax label="Orçamento total desta pesquisa" bind:minimo={c.orcamentoMin} bind:maximo={c.orcamentoMax}/>
<footer><button onclick={()=>onaplicar({...CONTEXTO_PADRAO})}>Limpar</button><button class="primary" onclick={()=>onaplicar(c)}>Aplicar contexto</button></footer></section>
<style>.backdrop{position:fixed;inset:0;background:#040912dd;z-index:30}.sheet{position:fixed;z-index:31;right:0;top:0;bottom:0;width:min(500px,100%);overflow:auto;background:#101b2c;color:#edf3fb;padding:24px;font-family:Inter,system-ui,sans-serif}.close{float:right;border:0;background:none;color:white;font-size:26px}.sheet h2{font-family:Georgia,serif;font-size:38px;font-weight:500}.sheet h3{margin-top:24px}.sheet label{display:block;color:#aebdd0;font-size:11px;margin:10px 0}.sheet input,.sheet select{width:100%;margin-top:5px;background:#091421;border:1px solid #30425d;color:white;border-radius:10px;padding:11px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:8px}.cards button,.add{border:1px solid #2b3d58;background:#142138;color:white;border-radius:10px;padding:12px}.cards button.on{border-color:#f5a524;background:#302a18}.check input{width:auto;margin-right:7px}.two,.person{display:grid;grid-template-columns:1fr 1fr;gap:8px}.note{font-size:10px;color:#91a2b8}.sheet footer{position:sticky;bottom:-24px;background:#101b2cee;border-top:1px solid #293a55;padding:14px 0 24px;display:grid;grid-template-columns:90px 1fr;gap:8px}.sheet footer button{border:1px solid #344761;background:#142138;color:white;border-radius:10px;padding:12px}.sheet footer .primary{background:#f5a524;color:#111;border:0;font-weight:700}</style>
