<script>
 import { CONTEXTO_PADRAO } from './dados.js';
 let {contexto,onaplicar,oncancelar}=$props();
 let c=$state(JSON.parse(JSON.stringify({...CONTEXTO_PADRAO,...(contexto??{}),dogs:{...CONTEXTO_PADRAO.dogs,...(contexto?.dogs??{})}})));
 let outros=$state(false);
 const principais=[['filhos','Com filhos'],['dogs','Com dogs'],['pais','Com os pais']];
 const extras=[['amigos','Com amigos'],['outros','Com outros']];
 const ocasioes=['','Aniversário','Aniversário da dupla','Dia dos Namorados','Dia das Mães','Dia dos Pais','Natal','Réveillon','Celebração especial'];
 const ativo=(id)=>c.companhias.includes(id);
 function toggle(id){c.companhias=ativo(id)?c.companhias.filter(x=>x!==id):[...c.companhias,id];if(id==='dogs'&&!c.dogs.quantidade)c.dogs.quantidade=1;if(id==='filhos'&&!c.filhos.length)c.filhos=[{idade:0}];if(id==='pais'&&!c.pais.length)c.pais=[{idade:null,mobilidadeReduzida:false}]}
</script>
<div class="backdrop"></div><section class="sheet"><button class="close" onclick={oncancelar}>×</button><small>CONTEXTO DESTA BUSCA</small><h2>Quem vai desta vez?</h2><div class="chips"><button class:on={!c.companhias.length} onclick={()=>c.companhias=[]}>Só vocês</button>{#each principais as [id,l]}<button class:on={ativo(id)} onclick={()=>toggle(id)}>{l}</button>{/each}<button class:on={outros} onclick={()=>outros=!outros}>Com outros ···</button></div>{#if outros}<div class="chips extras">{#each extras as [id,l]}<button class:on={ativo(id)} onclick={()=>toggle(id)}>{l}</button>{/each}</div>{/if}
{#if ativo('dogs')}<div class="detail"><h3>Dogs</h3><label>Quantidade<input type="number" min="1" bind:value={c.dogs.quantidade}/></label><p>Só mostraremos locais com aceitação de pets confirmada.</p></div>{/if}
{#if ativo('filhos')}<div class="detail"><h3>Idades das crianças</h3>{#each c.filhos as f,i}<label>Criança {i+1}<input type="number" min="0" max="17" bind:value={f.idade}/></label>{/each}<button onclick={()=>c.filhos=[...c.filhos,{idade:0}]}>+ Outra criança</button></div>{/if}
{#if ativo('pais')}<div class="detail"><h3>Pais</h3><label class="check"><input type="checkbox" bind:checked={c.pais[0].mobilidadeReduzida}/> Precisa de acessibilidade confirmada</label></div>{/if}
<h3>Quando e por quê</h3><label>Ocasião<select bind:value={c.ocasiao}>{#each ocasioes as o}<option value={o}>{o||'Sem ocasião específica'}</option>{/each}</select></label><div class="two"><label>De<input type="date" bind:value={c.dataInicio}/></label><label>Até<input type="date" bind:value={c.dataFim}/></label></div><div class="two"><label>Orçamento mínimo<input type="number" min="0" bind:value={c.orcamentoMin}/></label><label>Orçamento máximo<input type="number" min="0" bind:value={c.orcamentoMax}/></label></div>
<footer><button onclick={()=>onaplicar({...CONTEXTO_PADRAO})}>Limpar</button><button class="primary" onclick={()=>onaplicar(c)}>Aplicar contexto</button></footer></section>
<style>.backdrop{position:fixed;inset:0;background:#040912dd;z-index:30}.sheet{position:fixed;z-index:31;right:0;top:0;bottom:0;width:min(500px,100%);overflow:auto;background:#101b2c;color:#edf3fb;padding:24px;font-family:Inter,system-ui}.close{float:right;border:0;background:none;color:white;font-size:26px}.sheet h2{font:500 38px Georgia,serif}.sheet h3{margin-top:24px}.sheet label{display:block;color:#aebdd0;font-size:11px;margin:10px 0}.sheet input,.sheet select{width:100%;margin-top:5px;background:#091421;border:1px solid #30425d;color:white;border-radius:10px;padding:11px}.chips{display:flex;gap:7px;overflow:auto}.chips button,.detail button{white-space:nowrap;border:1px solid #2b3d58;background:#142138;color:white;border-radius:99px;padding:10px 12px}.chips button.on{border-color:#f5a524;background:#302a18}.extras{margin-top:8px}.detail{border:1px solid #293a55;border-radius:12px;padding:12px;margin-top:14px}.detail p{font-size:10px;color:#91a2b8}.check input{width:auto;margin-right:7px}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sheet footer{position:sticky;bottom:-24px;background:#101b2cee;border-top:1px solid #293a55;padding:14px 0 24px;display:grid;grid-template-columns:90px 1fr;gap:8px}.sheet footer button{border:1px solid #344761;background:#142138;color:white;border-radius:10px;padding:12px}.sheet footer .primary{background:#f5a524;color:#111;border:0;font-weight:700}</style>
