<script>
  import { PREFERENCIAS_PADRAO } from './dados.js';
  import { TIPOS } from './filtros.js';
  let { pessoa, cidadeBase='', onconcluir, oncancelar }=$props();
  let passo=$state(0), percurso=$state('');
  let nome=$state(pessoa?.nome??''), cidade=$state(cidadeBase), buscaAeroporto=$state('');
  let p=$state(JSON.parse(JSON.stringify({...PREFERENCIAS_PADRAO,...(pessoa?.preferencias??{}),hospedagem:{...PREFERENCIAS_PADRAO.hospedagem,...(pessoa?.preferencias?.hospedagem??{})},deslocamento:{...PREFERENCIAS_PADRAO.deslocamento,...(pessoa?.preferencias?.deslocamento??{})},orcamento:{...PREFERENCIAS_PADRAO.orcamento,...(pessoa?.preferencias?.orcamento??{})}})));
  const aeroportos=[['GRU','Guarulhos','Aeroporto Internacional'],['CGH','São Paulo','Congonhas'],['VCP','Campinas','Viracopos'],['SDU','Rio de Janeiro','Santos Dumont'],['GIG','Rio de Janeiro','Galeão'],['BSB','Brasília','Aeroporto Internacional'],['CNF','Belo Horizonte','Confins'],['POA','Porto Alegre','Salgado Filho'],['REC','Recife','Guararapes'],['SSA','Salvador','Aeroporto Internacional']];
  const atividades={praia:['mergulho','vela','praias tranquilas'],montanha:['esqui','trilhas','paisagens'],cultural:['museus','arquitetura','shows'],gastronomico:['alta gastronomia','vinícolas','comida local'],natureza:['observação de fauna','parques','ecoturismo'],aventura:['rafting','ciclismo','esportes radicais']};
  const formatos=[['bate_volta','Bate-e-volta','sem pernoite'],['fim_semana','Fim de semana','1–3 noites'],['ferias_7','Férias de 7 dias','viagem curta'],['ferias_14','Férias de 14 dias','viagem completa'],['ferias_21','Férias de 21 dias','imersão longa']];
  const niveis=[['economico','Econômico',2,4.0,50],['confortavel','Confortável',3,4.2,100],['superior','Superior',4,4.4,200],['excepcional','Excepcional',5,4.6,300]];
  const inegociaveis=[['acessibilidade','Acessibilidade confirmada'],['direto','Somente voo direto'],['nao_fumante','Ambiente não fumante'],['pet_friendly','Aceitar pets'],['adult_only','Somente para adultos'],['sem_madrugada','Sem voo de madrugada']];
  const toggle=(lista,v)=>lista.includes(v)?lista.filter(x=>x!==v):[...lista,v];
  const sugeridos=$derived(aeroportos.filter(([,cid,nome])=>!buscaAeroporto||`${cid} ${nome}`.toLowerCase().includes(buscaAeroporto.toLowerCase())).slice(0,6));
  function nivel(v){const n=niveis.find(x=>x[0]===v);p.hospedagem={...p.hospedagem,nivel:v,estrelasMin:n[2],avaliacaoMin:n[3],avaliacoesMin:n[4],aceitarSemClassificacao:false}}
  function favorito(id){p.experienciasFavoritas=toggle(p.experienciasFavoritas,id).slice(-3);if(!p.experiencias.includes(id))p.experiencias=[...p.experiencias,id]}
  function concluir(){onconcluir?.({nome,cidade,preferencias:{...p,percurso,aeroportos:p.aeroportos,onboardingCompleto:true}})}
  const total=$derived(percurso==='rapido'?5:8);
</script>
<div class="backdrop"></div><section class="wizard">
<header><div>{#if passo}<small>SEU PERFIL · {passo}/{total}</small><div class="progress"><i style={`width:${passo/total*100}%`}></i></div>{/if}</div>{#if oncancelar}<button aria-label="Fechar" onclick={oncancelar}>×</button>{/if}</header>
{#if passo===0}<p class="eyebrow">COMECE DO SEU JEITO</p><h2>Como você quer calibrar?</h2><div class="routes"><button onclick={()=>{percurso='rapido';passo=1}}><b>Perfil rápido</b><span>≈ 2 minutos · boas sugestões agora e melhora com o uso</span></button><button onclick={()=>{percurso='completo';passo=1}}><b>Perfil completo</b><span>≈ 8 minutos · maior precisão desde o início</span></button></div>
{:else if passo===1}<h2>Sobre você</h2><p>Cada pessoa configura o próprio perfil neste aparelho.</p><label>Seu nome<input bind:value={nome} placeholder="Como podemos chamar você?"/></label><label>Cidade-base<input bind:value={cidade} placeholder="Ex.: São Paulo"/></label><label>Aeroportos de origem<input bind:value={buscaAeroporto} placeholder="Busque por cidade ou aeroporto"/></label><div class="airport">{#each sugeridos as [id,cid,n]}<button class:on={p.aeroportos.includes(id)} onclick={()=>p.aeroportos=toggle(p.aeroportos,id)}><b>{cid} — {n}</b><span>{id} · toque para {p.aeroportos.includes(id)?'remover':'incluir'}</span></button>{/each}</div>
{:else if passo===2}<h2>O que faz valer a viagem?</h2><p>Marque tudo de que gosta. Depois destaque até três favoritos com ★.</p><div class="cards">{#each TIPOS as [id,emoji,label]}<div class:on={p.experiencias.includes(id)}><button onclick={()=>p.experiencias=toggle(p.experiencias,id)}>{emoji} {label}</button>{#if p.experiencias.includes(id)}<button class="star" aria-label={`Favoritar ${label}`} onclick={()=>favorito(id)}>{p.experienciasFavoritas.includes(id)?'★':'☆'}</button>{/if}</div>{/each}</div><small>{p.experiencias.length} interesses · {p.experienciasFavoritas.length}/3 favoritos</small>
{:else if passo===3}<h2>O que você gostaria de fazer?</h2><p>As atividades aparecem a partir das experiências escolhidas.</p><div class="cards">{#each p.experiencias.flatMap(x=>atividades[x]??[]) as a}<button class:on={p.atividades.includes(a)} onclick={()=>p.atividades=toggle(p.atividades,a)}>{a}</button>{/each}</div>
{:else if passo===4}<h2>Seu padrão de conforto</h2><p>Escolha uma referência. Você poderá ajustar os critérios no perfil completo.</p><div class="levels">{#each niveis as [id,label,e,a,q]}<button class:on={p.hospedagem.nivel===id} onclick={()=>nivel(id)}><b>{label}</b><span>{e}★ · nota {a}+ · {q}+ avaliações</span></button>{/each}</div>
{:else if passo===5}<h2>Como vocês costumam escapar?</h2><p>Ative todos os formatos que fazem parte da sua vida.</p><div class="levels">{#each formatos as [id,label,desc]}<button class:on={p.formatos.includes(id)} onclick={()=>p.formatos=toggle(p.formatos,id)}><b>{label}</b><span>{desc}</span></button>{/each}</div>
{:else if passo===6}<h2>Ajuste seu padrão</h2><p>Use opções discretas; nada de réguas milimétricas.</p><label>Estrelas mínimas<select bind:value={p.hospedagem.estrelasMin}><option value={3}>3 estrelas</option><option value={4}>4 estrelas</option><option value={5}>5 estrelas</option></select></label><label>Avaliação mínima<select bind:value={p.hospedagem.avaliacaoMin}><option value={4.0}>4,0</option><option value={4.3}>4,3</option><option value={4.5}>4,5</option><option value={4.7}>4,7</option></select></label><label>Mínimo de avaliações<select bind:value={p.hospedagem.avaliacoesMin}><option value={50}>50</option><option value={100}>100</option><option value={300}>300</option><option value={500}>500</option></select></label>
{:else if passo===7}<h2>Seus inegociáveis</h2><p>Somente condições objetivas que devem eliminar uma opção.</p><div class="cards">{#each inegociaveis as [id,label]}<button class:on={p.inegociaveis.includes(id)} onclick={()=>p.inegociaveis=toggle(p.inegociaveis,id)}>{label}</button>{/each}</div>
{:else}<h2>Sua próxima janela</h2><p>Escolha a intenção mais próxima. Outras janelas poderão ser criadas em Meus planos.</p><label>Formato<select value={p.janelas[0]?.formato??'fim_semana'} onchange={(e)=>p.janelas=[{...(p.janelas[0]??{}),formato:e.currentTarget.value}]}><option value="fim_semana">Fim de semana</option><option value="ferias_7">Férias · 7 dias</option><option value="ferias_14">Férias · 14 dias</option><option value="ferias_21">Férias · 21 dias</option></select></label><label>Quando<select onchange={(e)=>p.janelas=[{...(p.janelas[0]??{}),periodo:e.currentTarget.value}]}><option value="proximos_3_meses">Próximos 3 meses</option><option value="proximos_6_meses">Próximos 6 meses</option><option value="este_ano">Ainda este ano</option><option value="flexivel">Sem período definido</option></select></label>{/if}
{#if passo>0}<footer>{#if passo>1}<button onclick={()=>passo--}>Voltar</button>{/if}<span></span>{#if passo<total}<button class="primary" disabled={passo===1&&(!nome.trim()||!cidade.trim()||!p.aeroportos.length)} onclick={()=>passo++}>Continuar</button>{:else}<button class="primary" onclick={concluir}>Confirmar meu perfil</button>{/if}</footer>{/if}
</section>
<style>
.backdrop{position:fixed;inset:0;background:#040912ed;z-index:40}.wizard{position:fixed;inset:0;z-index:41;margin:auto;width:min(540px,100%);background:#0d1828;color:#edf3fb;padding:24px;overflow:auto;font-family:Inter,system-ui}.wizard header{display:flex}.wizard header>div{flex:1}.wizard header button{border:0;background:none;color:white;font-size:26px}.progress{height:3px;background:#263750;margin:10px 20px 22px 0}.progress i{display:block;height:100%;background:#f5a524}.wizard h2{font-family:Georgia,serif;font-size:38px;font-weight:500;margin:14px 0 8px}.wizard p,.wizard small{color:#91a2b8;line-height:1.5}.eyebrow{color:#f5a524!important;font-size:10px;letter-spacing:.2em}.wizard label{display:block;margin:16px 0;color:#aebdd0;font-size:12px}.wizard input,.wizard select{width:100%;margin-top:6px;background:#081321;border:1px solid #30425d;border-radius:10px;color:white;padding:12px}.routes,.levels,.airport{display:grid;gap:9px;margin:20px 0}.routes button,.levels button,.airport button{display:grid;gap:5px;text-align:left;border:1px solid #30425d;background:#142138;color:white;border-radius:14px;padding:16px}.routes span,.levels span,.airport span{font-size:10px;color:#91a2b8}.levels button.on,.airport button.on{border-color:#f5a524;background:#302a18}.cards{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.cards>button,.cards>div{border:1px solid #2b3d58;background:#142138;color:#dce5ef;border-radius:11px;padding:12px}.cards>div{display:flex;padding:0}.cards>div>button{flex:1;border:0;background:none;color:inherit;padding:12px}.cards>div .star{flex:0;font-size:20px;color:#f5a524}.cards .on,.cards button.on{border-color:#f5a524;background:#302a18;color:#ffe2a0}.wizard footer{position:sticky;bottom:-24px;display:flex;gap:8px;background:#0d1828ee;border-top:1px solid #293a55;padding:14px 0 24px;margin-top:25px}.wizard footer span{flex:1}.wizard footer button{border:1px solid #344761;background:#142138;color:white;border-radius:10px;padding:12px 16px}.wizard footer .primary{background:#f5a524;color:#111;border:0;font-weight:700}
</style>
