<script>
  import { PREFERENCIAS_PADRAO } from './dados.js';
  import { TIPOS } from './filtros.js';
  import Range from './Range.svelte';
  import MinMax from './MinMax.svelte';
  let { pessoa, cidadeBase = '', onconcluir, oncancelar } = $props();
  let passo = $state(1);
  let nome = $state(pessoa?.nome ?? '');
  let cidade = $state(cidadeBase);
  let aeroporto = $state((pessoa?.preferencias?.aeroportos ?? []).join(', '));
  let p = $state(structuredClone({ ...PREFERENCIAS_PADRAO, ...(pessoa?.preferencias ?? {}), hospedagem:{...PREFERENCIAS_PADRAO.hospedagem,...(pessoa?.preferencias?.hospedagem??{})}, deslocamento:{...PREFERENCIAS_PADRAO.deslocamento,...(pessoa?.preferencias?.deslocamento??{})}, orcamento:{...PREFERENCIAS_PADRAO.orcamento,...(pessoa?.preferencias?.orcamento??{})} }));
  const toggle = (lista, valor, max = 99) => lista.includes(valor) ? lista.filter((x)=>x!==valor) : lista.length < max ? [...lista,valor] : lista;
  const opcoesHospedagem = [['hotel','Hotel'],['resort','Resort'],['pousada','Pousada'],['boutique','Hotel-boutique'],['apartamento','Apartamento'],['adult_only','Adult-only']];
  const vetos = [['sem_classificacao','Sem classificação'],['avaliacao_insuficiente','Avaliação insuficiente'],['poucas_avaliacoes','Poucas avaliações'],['simples_demais','Simples demais'],['localizacao_afastada','Localização afastada'],['ambiente_infantil','Ambiente infantil'],['hotel_impessoal','Hotel grande e impessoal'],['madrugada','Voo de madrugada']];
  const calibracoes = [['hotel','Hotel tradicional','boutique','Boutique intimista'],['economia','Melhor preço','experiencia','Melhor experiência'],['cidade','Centro urbano','natureza','Natureza isolada'],['resort','Resort completo','pequeno','Propriedade pequena']];
  function concluir(){ onconcluir?.({nome,cidade,preferencias:{...p,aeroportos:aeroporto.split(',').map((x)=>x.trim().toUpperCase()).filter(Boolean),onboardingCompleto:true}}) }
</script>

<div class="backdrop"></div><section class="wizard">
  <header><div><small>SEU PERFIL · {passo}/7</small><div class="progress"><i style={`width:${passo/7*100}%`}></i></div></div>{#if oncancelar}<button aria-label="Fechar" onclick={oncancelar}>×</button>{/if}</header>
  {#if passo===1}<h2>Sobre você</h2><p>Cada pessoa configura o próprio perfil neste aparelho.</p><label>Seu nome<input bind:value={nome} placeholder="Como podemos chamar você?"/></label><label>Cidade-base<input bind:value={cidade} placeholder="Ex.: São Paulo"/></label><label>Aeroportos preferenciais<input bind:value={aeroporto} placeholder="Ex.: GRU, CGH"/></label>
  {:else if passo===2}<h2>O que faz valer a viagem?</h2><p>Escolha de 3 a 5 experiências.</p><div class="cards">{#each TIPOS as [id,emoji,label]}<button class:on={p.experiencias.includes(id)} onclick={()=>p.experiencias=toggle(p.experiencias,id,5)}>{emoji} {label}</button>{/each}</div><small>{p.experiencias.length} de 5 escolhidas</small>
  {:else if passo===3}<h2>Seu padrão de hospedagem</h2><p>Marque tipos aceitos e ative apenas as réguas importantes para você.</p><div class="cards">{#each opcoesHospedagem as [id,label]}<button class:on={p.hospedagemTipos.includes(id)} onclick={()=>p.hospedagemTipos=toggle(p.hospedagemTipos,id)}>{label}</button>{/each}</div><Range label="Categoria mínima" bind:value={p.hospedagem.estrelasMin} min={1} max={5} step={1} sufixo=" estrelas"/><Range label="Avaliação mínima" bind:value={p.hospedagem.avaliacaoMin} min={1} max={5} step={0.1}/><Range label="Quantidade mínima de avaliações" bind:value={p.hospedagem.avaliacoesMin} min={0} max={3000} step={50}/><label class="switch"><input type="checkbox" bind:checked={p.hospedagem.aceitarSemClassificacao}/> Aceito opções sem categoria informada</label>
  {:else if passo===4}<h2>Como você prefere viajar?</h2><Range label="Tempo máximo de carro" bind:value={p.deslocamento.carroMinutosMax} min={30} max={480} step={30} sufixo=" min"/><Range label="Mínimo de noites" bind:value={p.deslocamento.noitesMin} min={0} max={30} step={1}/><Range label="Máximo de noites" bind:value={p.deslocamento.noitesMax} min={1} max={45} step={1}/><div class="choice"><b>Máximo de escalas</b>{#each [[0,'Direto'],[1,'Até uma'],[2,'Até duas'],[null,'Tanto faz']] as [v,l]}<button class:on={p.deslocamento.escalasMax===v} onclick={()=>p.deslocamento.escalasMax=v}>{l}</button>{/each}</div><label class="switch"><input type="checkbox" bind:checked={p.deslocamento.evitarMadrugada}/> Evitar voos de madrugada</label><label class="switch"><input type="checkbox" bind:checked={p.deslocamento.bagagemObrigatoria}/> Bagagem incluída</label>
  {:else if passo===5}<h2>Quanto faz sentido gastar?</h2><p>Defina livremente o mínimo e o máximo. Deixe em branco se não quiser limitar.</p><MinMax label="Hospedagem por noite" bind:minimo={p.orcamento.diariaMin} bind:maximo={p.orcamento.diariaMax}/><MinMax label="Escapada completa" bind:minimo={p.orcamento.escapadaMin} bind:maximo={p.orcamento.escapadaMax}/><MinMax label="Viagem completa" bind:minimo={p.orcamento.viagemMin} bind:maximo={p.orcamento.viagemMax}/><label class="switch"><input type="checkbox" bind:checked={p.orcamento.extrapolaEspecial}/> Posso ultrapassar em ocasiões especiais</label>
  {:else if passo===6}<h2>O que você não quer ver?</h2><p>Marque somente o que realmente deve eliminar uma opção.</p><div class="cards">{#each vetos as [id,label]}<button class:on={p.inegociaveis.includes(id)} onclick={()=>p.inegociaveis=toggle(p.inegociaveis,id)}>{label}</button>{/each}</div>
  {:else}<h2>Calibração rápida</h2><p>Escolha o lado que mais representa você. “Nenhum” também é uma resposta.</p>{#each calibracoes as [a,la,b,lb]}<div class="pair"><button class:on={p.calibracao[a+'_'+b]===a} onclick={()=>p.calibracao[a+'_'+b]=a}>{la}</button><button class:on={p.calibracao[a+'_'+b]===b} onclick={()=>p.calibracao[a+'_'+b]=b}>{lb}</button><button class:on={p.calibracao[a+'_'+b]==='nenhum'} onclick={()=>p.calibracao[a+'_'+b]='nenhum'}>Nenhum</button></div>{/each}{/if}
  <footer>{#if passo>1}<button onclick={()=>passo--}>Voltar</button>{/if}<span></span>{#if passo<7}<button class="primary" disabled={passo===1&&(!nome.trim()||!cidade.trim())} onclick={()=>passo++}>Continuar</button>{:else}<button class="primary" onclick={concluir}>Confirmar meu perfil</button>{/if}</footer>
</section>

<style>
  .backdrop{position:fixed;inset:0;background:#040912ed;z-index:40}.wizard{position:fixed;inset:0;z-index:41;margin:auto;width:min(520px,100%);background:#0d1828;color:#edf3fb;padding:24px;overflow:auto;font-family:Inter,system-ui,sans-serif}.wizard header{display:flex;justify-content:space-between}.wizard header>div{flex:1}.wizard header button{border:0;background:none;color:white;font-size:26px}.progress{height:3px;background:#263750;margin:10px 20px 22px 0}.progress i{display:block;height:100%;background:#f5a524}.wizard h2{font-family:Georgia,serif;font-size:36px;font-weight:500;margin:14px 0 8px}.wizard p,.wizard small{color:#91a2b8;line-height:1.5}.wizard label{display:block;margin:16px 0;color:#aebdd0;font-size:12px}.wizard input{width:100%;margin-top:6px;background:#081321;border:1px solid #30425d;border-radius:10px;color:white;padding:12px}.cards{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.cards button,.choice button,.pair button{border:1px solid #2b3d58;background:#142138;color:#dce5ef;border-radius:11px;padding:12px}.cards button.on,.choice button.on,.pair button.on{border-color:#f5a524;background:#302a18;color:#ffe2a0}.switch{border:1px solid #293a55;border-radius:10px;padding:12px}.switch input{width:auto;margin:0 8px 0 0}.choice{display:flex;flex-wrap:wrap;gap:7px;margin:18px 0}.choice b{width:100%}.pair{display:grid;grid-template-columns:1fr 1fr 70px;gap:6px;margin:10px 0}.pair button{padding:10px 6px;font-size:11px}.wizard footer{position:sticky;bottom:-24px;display:flex;gap:8px;background:#0d1828ee;border-top:1px solid #293a55;padding:14px 0 24px;margin-top:25px}.wizard footer span{flex:1}.wizard footer button{border:1px solid #344761;background:#142138;color:white;border-radius:10px;padding:12px 16px}.wizard footer .primary{background:#f5a524;color:#111;border:0;font-weight:700}
</style>
